FROM python:3.13-slim
WORKDIR /code
RUN curl -sSL https://install.python-poetry.org | python3 -

ENV PATH="/root/.local/bin:${PATH}"

COPY poetry.lock pyproject.toml ./

RUN poetry install --no-dev

# Copy the entire project
COPY . .

# Expose the port that the application will run on
EXPOSE 8000

CMD [ "fastapi", "run", "main.py", "--host", "0.0.0.0", "--port", "8000" ]
